-- Facebook reference tables: exact schema to match existing setup.
-- Safe to run: CREATE TABLE IF NOT EXISTS and CREATE INDEX IF NOT EXISTS.

-- Facebook adset reference data
CREATE TABLE IF NOT EXISTS public.facebook_adset_reference_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  adset_name character varying(255) NULL,
  country character varying(255) NULL,
  product_type character varying(255) NULL,
  CONSTRAINT facebook_adset_reference_data_pkey PRIMARY KEY (id),
  CONSTRAINT facebook_adset_reference_data_adset_name_key UNIQUE (adset_name)
);

CREATE INDEX IF NOT EXISTS idx_adset_name ON public.facebook_adset_reference_data USING btree (adset_name);
CREATE INDEX IF NOT EXISTS idx_country ON public.facebook_adset_reference_data USING btree (country);
CREATE INDEX IF NOT EXISTS idx_product_type ON public.facebook_adset_reference_data USING btree (product_type);

-- Facebook campaigns reference data (no unique on campaign_name)
CREATE TABLE IF NOT EXISTS public.facebook_campaigns_reference_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  campaign_id character varying(50) NULL,
  campaign_name character varying(255) NULL,
  country character varying(255) NULL,
  product_type character varying(255) NULL,
  showname character varying(255) NULL,
  CONSTRAINT facebook_campaigns_reference_data_pkey PRIMARY KEY (id)
);
