-- Reddit campaigns ad group / campaign-level metrics (for Reddit Report dashboard).
-- Populated by fetch-reddit-campaigns Edge Function.
CREATE TABLE IF NOT EXISTS public.reddit_campaigns_ad_group (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  account_id character varying(50) NULL,
  campaign_id character varying(100) NULL,
  campaign_name character varying(255) NULL,
  ad_group_id character varying(100) NULL,
  ad_group_name character varying(255) NULL,
  community character varying(255) NULL,
  campaign_date date NULL,
  impressions bigint NULL,
  clicks bigint NULL,
  amount_spent_usd numeric(12,4) NULL,
  total_spent numeric(12,4) NULL,
  purchase_click bigint NULL,
  total_purchase_click bigint NULL,
  purchase_view bigint NULL,
  total_purchase_view bigint NULL,
  total_value_purchase numeric(12,4) NULL,
  total_records bigint NULL,
  unique_campaigns bigint NULL,
  CONSTRAINT reddit_campaigns_ad_group_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_reddit_ad_group_campaign_date ON public.reddit_campaigns_ad_group (campaign_date);
CREATE INDEX IF NOT EXISTS idx_reddit_ad_group_account ON public.reddit_campaigns_ad_group (account_id);
CREATE INDEX IF NOT EXISTS idx_reddit_ad_group_campaign_name ON public.reddit_campaigns_ad_group (campaign_name);

ALTER TABLE public.reddit_campaigns_ad_group ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated select reddit_campaigns_ad_group"
  ON public.reddit_campaigns_ad_group FOR SELECT TO authenticated USING (true);
CREATE POLICY "Service role all reddit_campaigns_ad_group"
  ON public.reddit_campaigns_ad_group FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Reddit campaigns placement / community-level metrics (optional; used for placement breakdown).
CREATE TABLE IF NOT EXISTS public.reddit_campaigns_placement (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  account_id character varying(50) NULL,
  campaign_date date NULL,
  name character varying(255) NULL,
  placement character varying(255) NULL,
  community character varying(255) NULL,
  impressions bigint NULL,
  clicks bigint NULL,
  amount_spent_usd numeric(12,4) NULL,
  purchase_click bigint NULL,
  purchase_view bigint NULL,
  CONSTRAINT reddit_campaigns_placement_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_reddit_placement_campaign_date ON public.reddit_campaigns_placement (campaign_date);
CREATE INDEX IF NOT EXISTS idx_reddit_placement_account ON public.reddit_campaigns_placement (account_id);

ALTER TABLE public.reddit_campaigns_placement ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated select reddit_campaigns_placement"
  ON public.reddit_campaigns_placement FOR SELECT TO authenticated USING (true);
CREATE POLICY "Service role all reddit_campaigns_placement"
  ON public.reddit_campaigns_placement FOR ALL TO service_role USING (true) WITH CHECK (true);
