-- TikTok Ads: fact table + upsert key + sync-by-date (reference table already exists in 20250312110000).

CREATE TABLE IF NOT EXISTS public.tiktok_campaigns_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  campaign_name character varying(255) NULL,
  campaign_id character varying(50) NULL,
  campaign_type character varying(100) NULL,
  ad_group_name character varying(255) NULL,
  ad_group_id character varying(50) NULL,
  ad_name character varying(500) NULL,
  ad_id character varying(50) NULL,
  creative_url text NULL,
  date date NOT NULL,
  placement character varying(100) NULL,
  cost numeric(12, 4) NULL,
  cpm numeric(12, 4) NULL,
  impressions bigint NULL,
  clicks bigint NULL,
  ctr numeric(8, 4) NULL,
  conversions integer NULL,
  cost_per_conversion numeric(12, 4) NULL,
  total_purchase integer NULL,
  purchase_roas numeric(12, 4) NULL,
  currency character varying(10) NULL,
  country character varying(100) NULL,
  product_type character varying(100) NULL,
  show_event character varying(255) NULL,
  CONSTRAINT tiktok_campaigns_data_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_tiktok_campaigns_data_date ON public.tiktok_campaigns_data (date DESC);
CREATE INDEX IF NOT EXISTS idx_tiktok_campaigns_data_campaign_id ON public.tiktok_campaigns_data (campaign_id);
CREATE INDEX IF NOT EXISTS idx_tiktok_campaigns_data_ad_id ON public.tiktok_campaigns_data (ad_id);

DROP INDEX IF EXISTS public.tiktok_campaigns_data_upsert_key;
-- PG 15+: one row per ad/day/placement (sync only inserts non-empty ad_id)
CREATE UNIQUE INDEX tiktok_campaigns_data_upsert_key
  ON public.tiktok_campaigns_data (ad_id, date, placement)
  NULLS NOT DISTINCT;

ALTER TABLE public.tiktok_campaigns_data ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated select tiktok_campaigns_data" ON public.tiktok_campaigns_data;
CREATE POLICY "Authenticated select tiktok_campaigns_data"
  ON public.tiktok_campaigns_data FOR SELECT TO authenticated USING (true);

-- Sync history (Settings → TikTok sync log)
CREATE TABLE IF NOT EXISTS public.tiktok_ads_sync_by_date (
  id BIGSERIAL PRIMARY KEY,
  account_id TEXT NOT NULL,
  segment_date DATE NOT NULL,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (account_id, segment_date)
);
CREATE INDEX IF NOT EXISTS idx_tiktok_ads_sync_by_date_d ON public.tiktok_ads_sync_by_date (segment_date DESC);
ALTER TABLE public.tiktok_ads_sync_by_date ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated read tiktok_ads_sync_by_date" ON public.tiktok_ads_sync_by_date;
CREATE POLICY "Authenticated read tiktok_ads_sync_by_date"
  ON public.tiktok_ads_sync_by_date FOR SELECT TO authenticated USING (true);
