-- Reddit and TikTok campaigns reference data (id, campaign_name, country, product_type, showname)
CREATE TABLE IF NOT EXISTS public.reddit_campaigns_reference_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  campaign_name character varying(255) NULL,
  country character varying(255) NULL,
  product_type character varying(255) NULL,
  showname character varying(255) NULL,
  CONSTRAINT reddit_campaigns_reference_data_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tiktok_campaigns_reference_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  campaign_name character varying(255) NULL,
  country character varying(255) NULL,
  product_type character varying(255) NULL,
  showname character varying(255) NULL,
  CONSTRAINT tiktok_campaigns_reference_data_pkey PRIMARY KEY (id)
);

-- Facebook campaigns reference data
CREATE TABLE IF NOT EXISTS public.facebook_campaigns_reference_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id character varying(50) NULL,
  campaign_name character varying(255) NULL,
  country character varying(255) NULL,
  product_type character varying(255) NULL,
  showname character varying(255) NULL
);

-- Facebook adset reference data
CREATE TABLE IF NOT EXISTS public.facebook_adset_reference_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  adset_name character varying(255) NULL,
  country character varying(255) NULL,
  product_type character varying(255) NULL,
  CONSTRAINT facebook_adset_reference_data_adset_name_key UNIQUE (adset_name)
);

-- RLS: allow authenticated users to select and update all reference tables
ALTER TABLE public.reddit_campaigns_reference_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tiktok_campaigns_reference_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facebook_campaigns_reference_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facebook_adset_reference_data ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated select reddit_campaigns_reference_data"
  ON public.reddit_campaigns_reference_data FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated update reddit_campaigns_reference_data"
  ON public.reddit_campaigns_reference_data FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated select tiktok_campaigns_reference_data"
  ON public.tiktok_campaigns_reference_data FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated update tiktok_campaigns_reference_data"
  ON public.tiktok_campaigns_reference_data FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated select facebook_campaigns_reference_data"
  ON public.facebook_campaigns_reference_data FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated update facebook_campaigns_reference_data"
  ON public.facebook_campaigns_reference_data FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated select facebook_adset_reference_data"
  ON public.facebook_adset_reference_data FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated update facebook_adset_reference_data"
  ON public.facebook_adset_reference_data FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
