-- Microsoft (Bing) Ads: mirror Reddit-style fact + reference tables for the dashboard.
-- Populate via SQL, import, or your own pipeline (no Edge Functions in this repo).

CREATE TABLE IF NOT EXISTS public.microsoft_campaigns_ad_group (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  account_id character varying(50) NULL,
  campaign_id character varying(100) NULL,
  campaign_name character varying(255) NULL,
  ad_group_id character varying(100) NULL,
  ad_group_name character varying(255) NULL,
  community character varying(255) NULL,
  campaign_date date NULL,
  impressions bigint NULL,
  clicks bigint NULL,
  amount_spent_usd numeric(12,4) NULL,
  total_spent numeric(12,4) NULL,
  purchase_click bigint NULL,
  total_purchase_click bigint NULL,
  purchase_view bigint NULL,
  total_purchase_view bigint NULL,
  total_value_purchase numeric(12,4) NULL,
  total_records bigint NULL,
  unique_campaigns bigint NULL,
  CONSTRAINT microsoft_campaigns_ad_group_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_microsoft_ad_group_campaign_date ON public.microsoft_campaigns_ad_group (campaign_date);
CREATE INDEX IF NOT EXISTS idx_microsoft_ad_group_account ON public.microsoft_campaigns_ad_group (account_id);
CREATE INDEX IF NOT EXISTS idx_microsoft_ad_group_campaign_name ON public.microsoft_campaigns_ad_group (campaign_name);

ALTER TABLE public.microsoft_campaigns_ad_group ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated select microsoft_campaigns_ad_group"
  ON public.microsoft_campaigns_ad_group FOR SELECT TO authenticated USING (true);
CREATE POLICY "Service role all microsoft_campaigns_ad_group"
  ON public.microsoft_campaigns_ad_group FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.microsoft_campaigns_placement (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  account_id character varying(50) NULL,
  campaign_id character varying(100) NULL,
  campaign_date date NULL,
  name character varying(255) NULL,
  placement character varying(255) NULL,
  community character varying(255) NULL,
  impressions bigint NULL,
  clicks bigint NULL,
  amount_spent_usd numeric(12,4) NULL,
  purchase_click bigint NULL,
  purchase_view bigint NULL,
  CONSTRAINT microsoft_campaigns_placement_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_microsoft_placement_campaign_date ON public.microsoft_campaigns_placement (campaign_date);
CREATE INDEX IF NOT EXISTS idx_microsoft_placement_account ON public.microsoft_campaigns_placement (account_id);

ALTER TABLE public.microsoft_campaigns_placement ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated select microsoft_campaigns_placement"
  ON public.microsoft_campaigns_placement FOR SELECT TO authenticated USING (true);
CREATE POLICY "Service role all microsoft_campaigns_placement"
  ON public.microsoft_campaigns_placement FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.microsoft_campaigns_reference_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  campaign_name character varying(255) NULL,
  country character varying(255) NULL,
  product_type character varying(255) NULL,
  showname character varying(255) NULL,
  CONSTRAINT microsoft_campaigns_reference_data_pkey PRIMARY KEY (id)
);

ALTER TABLE public.microsoft_campaigns_reference_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated select microsoft_campaigns_reference_data"
  ON public.microsoft_campaigns_reference_data FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated update microsoft_campaigns_reference_data"
  ON public.microsoft_campaigns_reference_data FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Service role all microsoft_campaigns_reference_data"
  ON public.microsoft_campaigns_reference_data FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.microsoft_ads_sync_by_date (
  id BIGSERIAL PRIMARY KEY,
  account_id TEXT NOT NULL,
  segment_date DATE NOT NULL,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (account_id, segment_date)
);
CREATE INDEX IF NOT EXISTS idx_microsoft_ads_sync_by_date_d ON public.microsoft_ads_sync_by_date (segment_date DESC);
ALTER TABLE public.microsoft_ads_sync_by_date ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated read microsoft_ads_sync_by_date" ON public.microsoft_ads_sync_by_date;
CREATE POLICY "Authenticated read microsoft_ads_sync_by_date"
  ON public.microsoft_ads_sync_by_date FOR SELECT TO authenticated USING (true);

CREATE UNIQUE INDEX IF NOT EXISTS microsoft_campaigns_ad_group_upsert_key
  ON public.microsoft_campaigns_ad_group (account_id, campaign_date, campaign_name, ad_group_name)
  NULLS NOT DISTINCT;

CREATE UNIQUE INDEX IF NOT EXISTS microsoft_campaigns_placement_upsert_key
  ON public.microsoft_campaigns_placement (account_id, campaign_id, campaign_date, placement)
  NULLS NOT DISTINCT;

ALTER TABLE public.ads_sync_by_date_log
  DROP CONSTRAINT IF EXISTS ads_sync_by_date_log_platform_check;

ALTER TABLE public.ads_sync_by_date_log
  ADD CONSTRAINT ads_sync_by_date_log_platform_check CHECK (platform IN (
    'google_ads', 'reddit_ads', 'facebook_ads', 'tiktok_ads', 'microsoft_ads'
  ));
