-- Facebook campaigns performance data (synced from Meta Marketing API).
-- If the table already exists with this schema, CREATE TABLE IF NOT EXISTS and indexes are no-ops.
CREATE TABLE IF NOT EXISTS public.facebook_campaigns_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  account_id character varying(50) NOT NULL,
  campaign_name character varying(255) NULL,
  adset_name character varying(255) NULL,
  ad_name character varying(255) NULL,
  placement character varying(100) NULL,
  day date NOT NULL,
  campaign_id character varying(50) NULL,
  adset_id character varying(50) NULL,
  ad_id character varying(50) NULL,
  platform character varying(50) NULL,
  device_platform character varying(50) NULL,
  delivery_status character varying(50) NULL,
  delivery_level character varying(20) NULL,
  reach bigint NULL,
  impressions bigint NULL,
  frequency numeric(10, 4) NULL,
  attribution_setting character varying(100) NULL,
  result_type character varying(100) NULL,
  results integer NULL,
  amount_spent_usd numeric(12, 4) NULL,
  cost_per_result numeric(12, 4) NULL,
  meta_purchases integer NULL,
  clicks_all bigint NULL,
  purchases integer NULL,
  inapp_purchase_roas numeric(10, 4) NULL,
  direct_website_purchases integer NULL,
  direct_website_purchases_value numeric(12, 4) NULL,
  inapp_purchases_value numeric(12, 4) NULL,
  website_purchases integer NULL,
  offline_purchases integer NULL,
  purchases_value numeric(12, 4) NULL,
  shops_assisted_purchases integer NULL,
  inapp_purchases integer NULL,
  website_purchases_value numeric(12, 4) NULL,
  offline_purchases_value numeric(12, 4) NULL,
  meta_purchase_value numeric(12, 4) NULL,
  reporting_starts date NULL,
  reporting_ends date NULL,
  created_at timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT facebook_campaigns_data_pkey PRIMARY KEY (id),
  CONSTRAINT facebook_unique_insight UNIQUE (ad_id, day, platform, placement, device_platform)
);

CREATE INDEX IF NOT EXISTS idx_fcd_account_id ON public.facebook_campaigns_data USING btree (account_id);
CREATE INDEX IF NOT EXISTS idx_fcd_campaign_id ON public.facebook_campaigns_data USING btree (campaign_id);
CREATE INDEX IF NOT EXISTS idx_fcd_adset_id ON public.facebook_campaigns_data USING btree (adset_id);
CREATE INDEX IF NOT EXISTS idx_fcd_ad_id ON public.facebook_campaigns_data USING btree (ad_id);
CREATE INDEX IF NOT EXISTS idx_fcd_day ON public.facebook_campaigns_data USING btree (day);
CREATE INDEX IF NOT EXISTS idx_fcd_platform ON public.facebook_campaigns_data USING btree (platform);
CREATE INDEX IF NOT EXISTS idx_fcd_device_platform ON public.facebook_campaigns_data USING btree (device_platform);
CREATE INDEX IF NOT EXISTS idx_fcd_delivery_status ON public.facebook_campaigns_data USING btree (delivery_status);
CREATE INDEX IF NOT EXISTS idx_fcd_account_day ON public.facebook_campaigns_data USING btree (account_id, day);
CREATE INDEX IF NOT EXISTS idx_fcd_campaign_day ON public.facebook_campaigns_data USING btree (campaign_id, day);
CREATE INDEX IF NOT EXISTS idx_fcd_adset_day ON public.facebook_campaigns_data USING btree (adset_id, day);
CREATE INDEX IF NOT EXISTS idx_fcd_ad_day ON public.facebook_campaigns_data USING btree (ad_id, day);
CREATE INDEX IF NOT EXISTS idx_fcd_reporting ON public.facebook_campaigns_data USING btree (reporting_starts, reporting_ends);
CREATE INDEX IF NOT EXISTS idx_fcd_created_at ON public.facebook_campaigns_data USING btree (created_at);

ALTER TABLE public.facebook_campaigns_data ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated select facebook_campaigns_data" ON public.facebook_campaigns_data;
CREATE POLICY "Authenticated select facebook_campaigns_data"
  ON public.facebook_campaigns_data FOR SELECT TO authenticated USING (true);
