-- Create country-aware Microsoft Ads sync tables without changing legacy Microsoft tables/functions.

CREATE TABLE IF NOT EXISTS public.microsoft_campaigns_ad_group_country (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  account_id character varying(50) NULL,
  campaign_id character varying(100) NULL,
  campaign_name character varying(255) NULL,
  ad_group_id character varying(100) NULL,
  ad_group_name character varying(255) NULL,
  community character varying(255) NULL,
  campaign_date date NULL,
  impressions bigint NULL,
  clicks bigint NULL,
  amount_spent_usd numeric(12,4) NULL,
  total_spent numeric(12,4) NULL,
  purchase_click bigint NULL,
  total_purchase_click bigint NULL,
  purchase_view bigint NULL,
  total_purchase_view bigint NULL,
  total_value_purchase numeric(12,4) NULL,
  total_records bigint NULL,
  unique_campaigns bigint NULL,
  country character varying(100) NULL,
  CONSTRAINT microsoft_campaigns_ad_group_country_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_microsoft_ad_group_country_campaign_date
  ON public.microsoft_campaigns_ad_group_country (campaign_date);
CREATE INDEX IF NOT EXISTS idx_microsoft_ad_group_country_account
  ON public.microsoft_campaigns_ad_group_country (account_id);
CREATE INDEX IF NOT EXISTS idx_microsoft_ad_group_country_campaign_name
  ON public.microsoft_campaigns_ad_group_country (campaign_name);
CREATE INDEX IF NOT EXISTS idx_microsoft_ad_group_country_country
  ON public.microsoft_campaigns_ad_group_country (country);

ALTER TABLE public.microsoft_campaigns_ad_group_country ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated select microsoft_campaigns_ad_group_country" ON public.microsoft_campaigns_ad_group_country;
CREATE POLICY "Authenticated select microsoft_campaigns_ad_group_country"
  ON public.microsoft_campaigns_ad_group_country FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "Service role all microsoft_campaigns_ad_group_country" ON public.microsoft_campaigns_ad_group_country;
CREATE POLICY "Service role all microsoft_campaigns_ad_group_country"
  ON public.microsoft_campaigns_ad_group_country FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE UNIQUE INDEX IF NOT EXISTS microsoft_campaigns_ad_group_country_upsert_key
  ON public.microsoft_campaigns_ad_group_country (account_id, campaign_date, campaign_name, ad_group_name, country)
  NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS public.microsoft_campaigns_placement_country (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  account_id character varying(50) NULL,
  campaign_id character varying(100) NULL,
  campaign_date date NULL,
  name character varying(255) NULL,
  placement character varying(255) NULL,
  community character varying(255) NULL,
  impressions bigint NULL,
  clicks bigint NULL,
  amount_spent_usd numeric(12,4) NULL,
  purchase_click bigint NULL,
  purchase_view bigint NULL,
  country character varying(100) NULL,
  CONSTRAINT microsoft_campaigns_placement_country_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_microsoft_placement_country_campaign_date
  ON public.microsoft_campaigns_placement_country (campaign_date);
CREATE INDEX IF NOT EXISTS idx_microsoft_placement_country_account
  ON public.microsoft_campaigns_placement_country (account_id);
CREATE INDEX IF NOT EXISTS idx_microsoft_placement_country_country
  ON public.microsoft_campaigns_placement_country (country);

ALTER TABLE public.microsoft_campaigns_placement_country ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated select microsoft_campaigns_placement_country" ON public.microsoft_campaigns_placement_country;
CREATE POLICY "Authenticated select microsoft_campaigns_placement_country"
  ON public.microsoft_campaigns_placement_country FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "Service role all microsoft_campaigns_placement_country" ON public.microsoft_campaigns_placement_country;
CREATE POLICY "Service role all microsoft_campaigns_placement_country"
  ON public.microsoft_campaigns_placement_country FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE UNIQUE INDEX IF NOT EXISTS microsoft_campaigns_placement_country_upsert_key
  ON public.microsoft_campaigns_placement_country (account_id, campaign_id, campaign_date, placement, country)
  NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS public.microsoft_ads_sync_by_date_country (
  id BIGSERIAL PRIMARY KEY,
  account_id TEXT NOT NULL,
  segment_date DATE NOT NULL,
  country TEXT NOT NULL,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (account_id, segment_date, country)
);

CREATE INDEX IF NOT EXISTS idx_microsoft_ads_sync_by_date_country_d
  ON public.microsoft_ads_sync_by_date_country (segment_date DESC);
CREATE INDEX IF NOT EXISTS idx_microsoft_ads_sync_by_date_country_country
  ON public.microsoft_ads_sync_by_date_country (country);

ALTER TABLE public.microsoft_ads_sync_by_date_country ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated read microsoft_ads_sync_by_date_country" ON public.microsoft_ads_sync_by_date_country;
CREATE POLICY "Authenticated read microsoft_ads_sync_by_date_country"
  ON public.microsoft_ads_sync_by_date_country FOR SELECT TO authenticated USING (true);

ALTER TABLE public.ads_sync_by_date_log
  DROP CONSTRAINT IF EXISTS ads_sync_by_date_log_platform_check;

ALTER TABLE public.ads_sync_by_date_log
  ADD CONSTRAINT ads_sync_by_date_log_platform_check CHECK (platform IN (
    'google_ads',
    'google_ads_country',
    'reddit_ads',
    'reddit_ads_country',
    'facebook_ads',
    'facebook_ads_country',
    'tiktok_ads',
    'tiktok_ads_country',
    'microsoft_ads',
    'microsoft_ads_country'
  ));
